repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        exclude: 'tests/test_prompts/.*'
    -   id: end-of-file-fixer
        exclude: 'tests/test_prompts/.*'
    -   id: check-yaml
